name: Release latest version on npm

on:
  release:
    types: [released]

jobs:
  release_to_npm:
    name: Release to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - run: npm install -g npm

      - run: yarn

      - name: Release to npm
        run: npm publish --provenance --access public
